//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_parkomata
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Зап об усл.
    /// </summary>
    // *** Start programmer edit section *** (ЗапОбУсл CustomAttributes)

    // *** End programmer edit section *** (ЗапОбУсл CustomAttributes)
    [AutoAltered()]
    [Caption("Зап об усл")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗапОбУслE", new string[] {
            "ВремяНачала as \'Время начала\'",
            "ДатаНачала as \'Дата начала\'",
            "ВремяОкон as \'Время окон\'",
            "ДатаОкон as \'Дата окон\'",
            "СтатОпл as \'Стат опл\'",
            "ВремяОплаты as \'Время оплаты\'",
            "ПаркМесто as \'Парк место\'",
            "ПаркМесто.Адрес as \'Адрес\'",
            "Автомобиль as \'Автомобиль\'",
            "Автомобиль.ГосНомер as \'Гос номер\'"}, Hidden=new string[] {
            "ПаркМесто.Адрес",
            "Автомобиль.ГосНомер"})]
    [MasterViewDefineAttribute("ЗапОбУслE", "ПаркМесто", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [MasterViewDefineAttribute("ЗапОбУслE", "Автомобиль", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ГосНомер")]
    public class ЗапОбУсл : ICSSoft.STORMNET.DataObject
    {
        
        private string fВремяНачала;
        
        private System.DateTime fДатаНачала = System.DateTime.Now;
        
        private string fВремяОкон;
        
        private System.DateTime fДатаОкон;
        
        private IIS.Prilozhenie_parkomata.Оплата fСтатОпл;
        
        private string fВремяОплаты;
        
        private IIS.Prilozhenie_parkomata.ПаркМесто fПаркМесто;
        
        private IIS.Prilozhenie_parkomata.Автомобиль fАвтомобиль;
        
        private IIS.Prilozhenie_parkomata.Услуга fУслуга;
        
        // *** Start programmer edit section *** (ЗапОбУсл CustomMembers)

        // *** End programmer edit section *** (ЗапОбУсл CustomMembers)

        
        /// <summary>
        /// ВремяНачала.
        /// </summary>
        // *** Start programmer edit section *** (ЗапОбУсл.ВремяНачала CustomAttributes)

        // *** End programmer edit section *** (ЗапОбУсл.ВремяНачала CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяНачала
        {
            get
            {
                // *** Start programmer edit section *** (ЗапОбУсл.ВремяНачала Get start)

                // *** End programmer edit section *** (ЗапОбУсл.ВремяНачала Get start)
                string result = this.fВремяНачала;
                // *** Start programmer edit section *** (ЗапОбУсл.ВремяНачала Get end)

                // *** End programmer edit section *** (ЗапОбУсл.ВремяНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗапОбУсл.ВремяНачала Set start)

                // *** End programmer edit section *** (ЗапОбУсл.ВремяНачала Set start)
                this.fВремяНачала = value;
                // *** Start programmer edit section *** (ЗапОбУсл.ВремяНачала Set end)

                // *** End programmer edit section *** (ЗапОбУсл.ВремяНачала Set end)
            }
        }
        
        /// <summary>
        /// ВремяОкон.
        /// </summary>
        // *** Start programmer edit section *** (ЗапОбУсл.ВремяОкон CustomAttributes)

        // *** End programmer edit section *** (ЗапОбУсл.ВремяОкон CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяОкон
        {
            get
            {
                // *** Start programmer edit section *** (ЗапОбУсл.ВремяОкон Get start)

                // *** End programmer edit section *** (ЗапОбУсл.ВремяОкон Get start)
                string result = this.fВремяОкон;
                // *** Start programmer edit section *** (ЗапОбУсл.ВремяОкон Get end)

                // *** End programmer edit section *** (ЗапОбУсл.ВремяОкон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗапОбУсл.ВремяОкон Set start)

                // *** End programmer edit section *** (ЗапОбУсл.ВремяОкон Set start)
                this.fВремяОкон = value;
                // *** Start programmer edit section *** (ЗапОбУсл.ВремяОкон Set end)

                // *** End programmer edit section *** (ЗапОбУсл.ВремяОкон Set end)
            }
        }
        
        /// <summary>
        /// ВремяОплаты.
        /// </summary>
        // *** Start programmer edit section *** (ЗапОбУсл.ВремяОплаты CustomAttributes)

        // *** End programmer edit section *** (ЗапОбУсл.ВремяОплаты CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяОплаты
        {
            get
            {
                // *** Start programmer edit section *** (ЗапОбУсл.ВремяОплаты Get start)

                // *** End programmer edit section *** (ЗапОбУсл.ВремяОплаты Get start)
                string result = this.fВремяОплаты;
                // *** Start programmer edit section *** (ЗапОбУсл.ВремяОплаты Get end)

                // *** End programmer edit section *** (ЗапОбУсл.ВремяОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗапОбУсл.ВремяОплаты Set start)

                // *** End programmer edit section *** (ЗапОбУсл.ВремяОплаты Set start)
                this.fВремяОплаты = value;
                // *** Start programmer edit section *** (ЗапОбУсл.ВремяОплаты Set end)

                // *** End programmer edit section *** (ЗапОбУсл.ВремяОплаты Set end)
            }
        }
        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ЗапОбУсл.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ЗапОбУсл.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ЗапОбУсл.ДатаНачала Get start)

                // *** End programmer edit section *** (ЗапОбУсл.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ЗапОбУсл.ДатаНачала Get end)

                // *** End programmer edit section *** (ЗапОбУсл.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗапОбУсл.ДатаНачала Set start)

                // *** End programmer edit section *** (ЗапОбУсл.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ЗапОбУсл.ДатаНачала Set end)

                // *** End programmer edit section *** (ЗапОбУсл.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкон.
        /// </summary>
        // *** Start programmer edit section *** (ЗапОбУсл.ДатаОкон CustomAttributes)

        // *** End programmer edit section *** (ЗапОбУсл.ДатаОкон CustomAttributes)
        public virtual System.DateTime ДатаОкон
        {
            get
            {
                // *** Start programmer edit section *** (ЗапОбУсл.ДатаОкон Get start)

                // *** End programmer edit section *** (ЗапОбУсл.ДатаОкон Get start)
                System.DateTime result = this.fДатаОкон;
                // *** Start programmer edit section *** (ЗапОбУсл.ДатаОкон Get end)

                // *** End programmer edit section *** (ЗапОбУсл.ДатаОкон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗапОбУсл.ДатаОкон Set start)

                // *** End programmer edit section *** (ЗапОбУсл.ДатаОкон Set start)
                this.fДатаОкон = value;
                // *** Start programmer edit section *** (ЗапОбУсл.ДатаОкон Set end)

                // *** End programmer edit section *** (ЗапОбУсл.ДатаОкон Set end)
            }
        }
        
        /// <summary>
        /// СтатОпл.
        /// </summary>
        // *** Start programmer edit section *** (ЗапОбУсл.СтатОпл CustomAttributes)

        // *** End programmer edit section *** (ЗапОбУсл.СтатОпл CustomAttributes)
        public virtual IIS.Prilozhenie_parkomata.Оплата СтатОпл
        {
            get
            {
                // *** Start programmer edit section *** (ЗапОбУсл.СтатОпл Get start)

                // *** End programmer edit section *** (ЗапОбУсл.СтатОпл Get start)
                IIS.Prilozhenie_parkomata.Оплата result = this.fСтатОпл;
                // *** Start programmer edit section *** (ЗапОбУсл.СтатОпл Get end)

                // *** End programmer edit section *** (ЗапОбУсл.СтатОпл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗапОбУсл.СтатОпл Set start)

                // *** End programmer edit section *** (ЗапОбУсл.СтатОпл Set start)
                this.fСтатОпл = value;
                // *** Start programmer edit section *** (ЗапОбУсл.СтатОпл Set end)

                // *** End programmer edit section *** (ЗапОбУсл.СтатОпл Set end)
            }
        }
        
        /// <summary>
        /// Зап об усл.
        /// </summary>
        // *** Start programmer edit section *** (ЗапОбУсл.Автомобиль CustomAttributes)

        // *** End programmer edit section *** (ЗапОбУсл.Автомобиль CustomAttributes)
        [PropertyStorage(new string[] {
                "Автомобиль"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_parkomata.Автомобиль Автомобиль
        {
            get
            {
                // *** Start programmer edit section *** (ЗапОбУсл.Автомобиль Get start)

                // *** End programmer edit section *** (ЗапОбУсл.Автомобиль Get start)
                IIS.Prilozhenie_parkomata.Автомобиль result = this.fАвтомобиль;
                // *** Start programmer edit section *** (ЗапОбУсл.Автомобиль Get end)

                // *** End programmer edit section *** (ЗапОбУсл.Автомобиль Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗапОбУсл.Автомобиль Set start)

                // *** End programmer edit section *** (ЗапОбУсл.Автомобиль Set start)
                this.fАвтомобиль = value;
                // *** Start programmer edit section *** (ЗапОбУсл.Автомобиль Set end)

                // *** End programmer edit section *** (ЗапОбУсл.Автомобиль Set end)
            }
        }
        
        /// <summary>
        /// Зап об усл.
        /// </summary>
        // *** Start programmer edit section *** (ЗапОбУсл.ПаркМесто CustomAttributes)

        // *** End programmer edit section *** (ЗапОбУсл.ПаркМесто CustomAttributes)
        [PropertyStorage(new string[] {
                "ПаркМесто"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_parkomata.ПаркМесто ПаркМесто
        {
            get
            {
                // *** Start programmer edit section *** (ЗапОбУсл.ПаркМесто Get start)

                // *** End programmer edit section *** (ЗапОбУсл.ПаркМесто Get start)
                IIS.Prilozhenie_parkomata.ПаркМесто result = this.fПаркМесто;
                // *** Start programmer edit section *** (ЗапОбУсл.ПаркМесто Get end)

                // *** End programmer edit section *** (ЗапОбУсл.ПаркМесто Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗапОбУсл.ПаркМесто Set start)

                // *** End programmer edit section *** (ЗапОбУсл.ПаркМесто Set start)
                this.fПаркМесто = value;
                // *** Start programmer edit section *** (ЗапОбУсл.ПаркМесто Set end)

                // *** End programmer edit section *** (ЗапОбУсл.ПаркМесто Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Prilozhenie_parkomata.Услуга.
        /// </summary>
        // *** Start programmer edit section *** (ЗапОбУсл.Услуга CustomAttributes)

        // *** End programmer edit section *** (ЗапОбУсл.Услуга CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Услуга"})]
        public virtual IIS.Prilozhenie_parkomata.Услуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (ЗапОбУсл.Услуга Get start)

                // *** End programmer edit section *** (ЗапОбУсл.Услуга Get start)
                IIS.Prilozhenie_parkomata.Услуга result = this.fУслуга;
                // *** Start programmer edit section *** (ЗапОбУсл.Услуга Get end)

                // *** End programmer edit section *** (ЗапОбУсл.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗапОбУсл.Услуга Set start)

                // *** End programmer edit section *** (ЗапОбУсл.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (ЗапОбУсл.Услуга Set end)

                // *** End programmer edit section *** (ЗапОбУсл.Услуга Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗапОбУслE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗапОбУслE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗапОбУслE", typeof(IIS.Prilozhenie_parkomata.ЗапОбУсл));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗапОбУсл.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗапОбУсл CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗапОбУсл CustomAttributes)
    public class DetailArrayOfЗапОбУсл : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Prilozhenie_parkomata.DetailArrayOfЗапОбУсл members)

        // *** End programmer edit section *** (IIS.Prilozhenie_parkomata.DetailArrayOfЗапОбУсл members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗапОбУсл by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗапОбУсл.
        /// </summary>
        public DetailArrayOfЗапОбУсл(IIS.Prilozhenie_parkomata.Услуга fУслуга) : 
                base(typeof(ЗапОбУсл), ((ICSSoft.STORMNET.DataObject)(fУслуга)))
        {
        }
        
        public IIS.Prilozhenie_parkomata.ЗапОбУсл this[int index]
        {
            get
            {
                return ((IIS.Prilozhenie_parkomata.ЗапОбУсл)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Prilozhenie_parkomata.ЗапОбУсл dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
