//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_parkomata
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Парковка.
    /// </summary>
    // *** Start programmer edit section *** (Парковка CustomAttributes)

    // *** End programmer edit section *** (Парковка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПарковкаE", new string[] {
            "НомПарковки as \'Ном парковки\'",
            "Адрес as \'Адрес\'"})]
    [AssociatedDetailViewAttribute("ПарковкаE", "Паркомат", "ПаркоматE", true, "", "Паркомат", true, new string[] {
            ""})]
    [View("ПарковкаL", new string[] {
            "НомПарковки as \'Ном парковки\'",
            "Адрес as \'Адрес\'"})]
    public class Парковка : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомПарковки;
        
        private string fАдрес;
        
        private IIS.Prilozhenie_parkomata.DetailArrayOfПаркомат fПаркомат;
        
        // *** Start programmer edit section *** (Парковка CustomMembers)

        // *** End programmer edit section *** (Парковка CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Парковка.Адрес CustomAttributes)

        // *** End programmer edit section *** (Парковка.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Парковка.Адрес Get start)

                // *** End programmer edit section *** (Парковка.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Парковка.Адрес Get end)

                // *** End programmer edit section *** (Парковка.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Парковка.Адрес Set start)

                // *** End programmer edit section *** (Парковка.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Парковка.Адрес Set end)

                // *** End programmer edit section *** (Парковка.Адрес Set end)
            }
        }
        
        /// <summary>
        /// НомПарковки.
        /// </summary>
        // *** Start programmer edit section *** (Парковка.НомПарковки CustomAttributes)

        // *** End programmer edit section *** (Парковка.НомПарковки CustomAttributes)
        public virtual int НомПарковки
        {
            get
            {
                // *** Start programmer edit section *** (Парковка.НомПарковки Get start)

                // *** End programmer edit section *** (Парковка.НомПарковки Get start)
                int result = this.fНомПарковки;
                // *** Start programmer edit section *** (Парковка.НомПарковки Get end)

                // *** End programmer edit section *** (Парковка.НомПарковки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Парковка.НомПарковки Set start)

                // *** End programmer edit section *** (Парковка.НомПарковки Set start)
                this.fНомПарковки = value;
                // *** Start programmer edit section *** (Парковка.НомПарковки Set end)

                // *** End programmer edit section *** (Парковка.НомПарковки Set end)
            }
        }
        
        /// <summary>
        /// Парковка.
        /// </summary>
        // *** Start programmer edit section *** (Парковка.Паркомат CustomAttributes)

        // *** End programmer edit section *** (Парковка.Паркомат CustomAttributes)
        public virtual IIS.Prilozhenie_parkomata.DetailArrayOfПаркомат Паркомат
        {
            get
            {
                // *** Start programmer edit section *** (Парковка.Паркомат Get start)

                // *** End programmer edit section *** (Парковка.Паркомат Get start)
                if ((this.fПаркомат == null))
                {
                    this.fПаркомат = new IIS.Prilozhenie_parkomata.DetailArrayOfПаркомат(this);
                }
                IIS.Prilozhenie_parkomata.DetailArrayOfПаркомат result = this.fПаркомат;
                // *** Start programmer edit section *** (Парковка.Паркомат Get end)

                // *** End programmer edit section *** (Парковка.Паркомат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Парковка.Паркомат Set start)

                // *** End programmer edit section *** (Парковка.Паркомат Set start)
                this.fПаркомат = value;
                // *** Start programmer edit section *** (Парковка.Паркомат Set end)

                // *** End programmer edit section *** (Парковка.Паркомат Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПарковкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПарковкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПарковкаE", typeof(IIS.Prilozhenie_parkomata.Парковка));
                }
            }
            
            /// <summary>
            /// "ПарковкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПарковкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПарковкаL", typeof(IIS.Prilozhenie_parkomata.Парковка));
                }
            }
        }
    }
}
