//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_parkomata
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Парк место.
    /// </summary>
    // *** Start programmer edit section *** (ПаркМесто CustomAttributes)

    // *** End programmer edit section *** (ПаркМесто CustomAttributes)
    [AutoAltered()]
    [Caption("Парк место")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПаркМестоE", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "Адрес as \'Адрес\'"})]
    [View("ПаркМестоL", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "Адрес as \'Адрес\'"})]
    public class ПаркМесто : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Prilozhenie_parkomata.Статусы fСтатус;
        
        private string fАдрес;
        
        // *** Start programmer edit section *** (ПаркМесто CustomMembers)

        // *** End programmer edit section *** (ПаркМесто CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (ПаркМесто.Адрес CustomAttributes)

        // *** End programmer edit section *** (ПаркМесто.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (ПаркМесто.Адрес Get start)

                // *** End programmer edit section *** (ПаркМесто.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (ПаркМесто.Адрес Get end)

                // *** End programmer edit section *** (ПаркМесто.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПаркМесто.Адрес Set start)

                // *** End programmer edit section *** (ПаркМесто.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (ПаркМесто.Адрес Set end)

                // *** End programmer edit section *** (ПаркМесто.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ПаркМесто.Номер CustomAttributes)

        // *** End programmer edit section *** (ПаркМесто.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ПаркМесто.Номер Get start)

                // *** End programmer edit section *** (ПаркМесто.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ПаркМесто.Номер Get end)

                // *** End programmer edit section *** (ПаркМесто.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПаркМесто.Номер Set start)

                // *** End programmer edit section *** (ПаркМесто.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ПаркМесто.Номер Set end)

                // *** End programmer edit section *** (ПаркМесто.Номер Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (ПаркМесто.Статус CustomAttributes)

        // *** End programmer edit section *** (ПаркМесто.Статус CustomAttributes)
        public virtual IIS.Prilozhenie_parkomata.Статусы Статус
        {
            get
            {
                // *** Start programmer edit section *** (ПаркМесто.Статус Get start)

                // *** End programmer edit section *** (ПаркМесто.Статус Get start)
                IIS.Prilozhenie_parkomata.Статусы result = this.fСтатус;
                // *** Start programmer edit section *** (ПаркМесто.Статус Get end)

                // *** End programmer edit section *** (ПаркМесто.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПаркМесто.Статус Set start)

                // *** End programmer edit section *** (ПаркМесто.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (ПаркМесто.Статус Set end)

                // *** End programmer edit section *** (ПаркМесто.Статус Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПаркМестоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПаркМестоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПаркМестоE", typeof(IIS.Prilozhenie_parkomata.ПаркМесто));
                }
            }
            
            /// <summary>
            /// "ПаркМестоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПаркМестоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПаркМестоL", typeof(IIS.Prilozhenie_parkomata.ПаркМесто));
                }
            }
        }
    }
}
