//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_parkomata
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Положения.
    /// </summary>
    // *** Start programmer edit section *** (Положения CustomAttributes)

    // *** End programmer edit section *** (Положения CustomAttributes)
    public enum Положения
    {
        
        // *** Start programmer edit section *** (Положения.1 CustomAttributes)

        // *** End programmer edit section *** (Положения.1 CustomAttributes)
        [Caption("открыт")]
        1,
        
        // *** Start programmer edit section *** (Положения.2 CustomAttributes)

        // *** End programmer edit section *** (Положения.2 CustomAttributes)
        [Caption("закрыт")]
        2,
    }
}
