//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_parkomata
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Стоимость.
    /// </summary>
    // *** Start programmer edit section *** (Стоимость CustomAttributes)

    // *** End programmer edit section *** (Стоимость CustomAttributes)
    public enum Стоимость
    {
        
        // *** Start programmer edit section *** (Стоимость.1 CustomAttributes)

        // *** End programmer edit section *** (Стоимость.1 CustomAttributes)
        [Caption("бесплатно")]
        1,
        
        // *** Start programmer edit section *** (Стоимость.2 CustomAttributes)

        // *** End programmer edit section *** (Стоимость.2 CustomAttributes)
        [Caption("150")]
        2,
        
        // *** Start programmer edit section *** (Стоимость.3 CustomAttributes)

        // *** End programmer edit section *** (Стоимость.3 CustomAttributes)
        [Caption("300")]
        3,
    }
}
