//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_parkomata
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Шлагбаум.
    /// </summary>
    // *** Start programmer edit section *** (Шлагбаум CustomAttributes)

    // *** End programmer edit section *** (Шлагбаум CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ШлагбаумE", new string[] {
            "Адрес as \'Адрес\'",
            "Положение as \'Положение\'",
            "НомШлаг as \'Номер шлагбаума\'"})]
    [View("ШлагбаумL", new string[] {
            "Адрес as \'Адрес\'",
            "Положение as \'Положение\'",
            "НомШлаг as \'Номер шлагбаума\'"})]
    public class Шлагбаум : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Prilozhenie_parkomata.Положения fПоложение;
        
        private string fАдрес;
        
        private int fНомШлаг;
        
        // *** Start programmer edit section *** (Шлагбаум CustomMembers)

        // *** End programmer edit section *** (Шлагбаум CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Шлагбаум.Адрес CustomAttributes)

        // *** End programmer edit section *** (Шлагбаум.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Шлагбаум.Адрес Get start)

                // *** End programmer edit section *** (Шлагбаум.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Шлагбаум.Адрес Get end)

                // *** End programmer edit section *** (Шлагбаум.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Шлагбаум.Адрес Set start)

                // *** End programmer edit section *** (Шлагбаум.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Шлагбаум.Адрес Set end)

                // *** End programmer edit section *** (Шлагбаум.Адрес Set end)
            }
        }
        
        /// <summary>
        /// НомШлаг.
        /// </summary>
        // *** Start programmer edit section *** (Шлагбаум.НомШлаг CustomAttributes)

        // *** End programmer edit section *** (Шлагбаум.НомШлаг CustomAttributes)
        public virtual int НомШлаг
        {
            get
            {
                // *** Start programmer edit section *** (Шлагбаум.НомШлаг Get start)

                // *** End programmer edit section *** (Шлагбаум.НомШлаг Get start)
                int result = this.fНомШлаг;
                // *** Start programmer edit section *** (Шлагбаум.НомШлаг Get end)

                // *** End programmer edit section *** (Шлагбаум.НомШлаг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Шлагбаум.НомШлаг Set start)

                // *** End programmer edit section *** (Шлагбаум.НомШлаг Set start)
                this.fНомШлаг = value;
                // *** Start programmer edit section *** (Шлагбаум.НомШлаг Set end)

                // *** End programmer edit section *** (Шлагбаум.НомШлаг Set end)
            }
        }
        
        /// <summary>
        /// Положение.
        /// </summary>
        // *** Start programmer edit section *** (Шлагбаум.Положение CustomAttributes)

        // *** End programmer edit section *** (Шлагбаум.Положение CustomAttributes)
        public virtual IIS.Prilozhenie_parkomata.Положения Положение
        {
            get
            {
                // *** Start programmer edit section *** (Шлагбаум.Положение Get start)

                // *** End programmer edit section *** (Шлагбаум.Положение Get start)
                IIS.Prilozhenie_parkomata.Положения result = this.fПоложение;
                // *** Start programmer edit section *** (Шлагбаум.Положение Get end)

                // *** End programmer edit section *** (Шлагбаум.Положение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Шлагбаум.Положение Set start)

                // *** End programmer edit section *** (Шлагбаум.Положение Set start)
                this.fПоложение = value;
                // *** Start programmer edit section *** (Шлагбаум.Положение Set end)

                // *** End programmer edit section *** (Шлагбаум.Положение Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ШлагбаумE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ШлагбаумE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ШлагбаумE", typeof(IIS.Prilozhenie_parkomata.Шлагбаум));
                }
            }
            
            /// <summary>
            /// "ШлагбаумL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ШлагбаумL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ШлагбаумL", typeof(IIS.Prilozhenie_parkomata.Шлагбаум));
                }
            }
        }
    }
}
